/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Teste13 */

#ifndef _Included_Teste13
#define _Included_Teste13
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Teste13
 * Method:    falar
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Teste13_falar
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
